services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${LETS_ENCRYPT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/acme.json:/letsencrypt/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  ocr_cli_runner:
    build:
      dockerfile: Dockerfile        # デフォルトなら省略可能
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: ocr_cli_runner
    volumes:
      - /home/azureuser/tmpdir:/root/tmpdir/img
      - ./app.py:/root/ocr_cli/app.py
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocr_cli_runner.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.ocr_cli_runner.entrypoints=websecure"
      - "traefik.http.routers.ocr_cli_runner.tls.certresolver=myresolver"
      - "traefik.http.services.ocr_cli_runner.loadbalancer.server.port=7860"
    command: ["python", "app.py"]  # コンテナ起動時に app.py を実行
