# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ndlocr2_gradio',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/ndlocr2_gradio',
                'lib_path': 'ndlocr2_gradio'},
  'syms': { 'ndlocr2_gradio.core': {'ndlocr2_gradio.core.foo': ('core.html#foo', 'ndlocr2_gradio/core.py')},
            'ndlocr2_gradio.input.pdf': {'ndlocr2_gradio.input.pdf.PdfClient': ('input/pdf.html#pdfclient', 'ndlocr2_gradio/input/pdf.py')},
            'ndlocr2_gradio.pdf': {'ndlocr2_gradio.pdf.PdfClient': ('pdf.html#pdfclient', 'ndlocr2_gradio/pdf.py')}}}
