"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/input/00_pdf.ipynb.

# %% auto 0
__all__ = ['PdfClient']

# %% ../../nbs/input/00_pdf.ipynb 3
class PdfClient:
    pass
